replicaCount: 3
service:
  name: interface
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  hosts:
    - ui.k8s.nonce.ch
  annotations:
     kubernetes.io/ingress.class: nginx

nginx-ingress:
  controller:
    config:
      root: /var/www
    service:
      targetPorts:
        http: 80
        https: 443
    replicaCount: 1

ui:
  image:
    repository: evanhenri/ui
    tag: 0.0.1
    pullPolicy: Always

api:
  image:
    repository: evanhenri/api
    tag: 0.0.1
    pullPolicy: Always

